### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [igormp/Imp#9]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by igormp** [comment]
Oops, forgot about that, added MIT so there shouldn't be any issues to do whatever you want with it :)

Fixed in https://github.com/igormp/Imp/commit/9918a238d968018bce7c0318faa64bc93f8ddc5d
